#!/usr/bin/env ruby

require 'json'

# terraform show -json plan-result
# terraform show -json plan-result > plan-result.json

$plan_file = ARGV.shift

# Refer address in https://www.terraform.io/docs/internals/json-format.html#plan-representation
class ResourceAddress
  def initialize(str_address)
    @str_address = str_address
    levels = @str_address.split('.')
    @resource_type = levels[-2]
    @resource_name = levels[-1]
  end

  def to_s
    @str_address
  end
end

def print_specific_action_resources(action_name)
  puts "# #{action_name}"
  tree = File.open($plan_file) do |file|
    JSON.load(file)
  end
  resource_addresses = tree['resource_changes'].
    select { |c| c['change']['actions'][0] == action_name }.
    map { |c| c['address'] }.
    map { |c| ResourceAddress.new(c) }
  puts resource_addresses
  puts
end

# # https://github.com/hashicorp/terraform-json/blob/7bf4a174/action.go#L11-L26
print_specific_action_resources 'create'
print_specific_action_resources 'update'
print_specific_action_resources 'delete'
